FROM sumeetchhetri/gatf-jar:latest

FROM selenium/standalone-chrome-debug:latest
  
ARG DEBIAN_FRONTEND=noninteractive

USER root
RUN apt update -y && apt install -y --no-install-recommends default-jdk git wget unzip net-tools && rm -rf /var/lib/apt/lists/*

COPY --from=0 /gatf-alldep.jar /
RUN sed -i'' -e "s|java |java -jar /gatf-alldep.jar -configtool 9080 0.0.0.0 /workdir > gatf.log 2>\&1 \&\\njava |g" /opt/bin/start-selenium-standalone.sh
