FROM sumeetchhetri/gatf-jar:latest

FROM dorowu/ubuntu-desktop-lxde-vnc
  
ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt update -y && apt install -y openjdk-11-jdk openjdk-11-jre git wget unzip net-tools && rm -rf /var/lib/apt/lists/*

COPY --from=0 /gatf-alldep.jar /
COPY artifacts/run-gatf.sh /
COPY artifacts/supervisord.conf /etc/supervisor/conf.d/
RUN chmod +x /run-gatf.sh

EXPOSE 9080
EXPOSE 5900
EXPOSE 80
