FROM sumeetchhetri/gatf-jar:latest

FROM ubuntu:20.04
  
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt install -y openjdk-11-jdk openjdk-11-jre git wget unzip net-tools gnupg && rm -rf /var/lib/apt/lists/*
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google.list
RUN apt update -y && apt install -y google-chrome-stable
RUN ln -s /usr/bin/google-chrome /usr/bin/chromium-browser

COPY --from=0 /gatf-alldep.jar /
COPY artifacts/run-gatf.sh /
RUN chmod +x /run-gatf.sh

EXPOSE 9080

CMD java -jar /gatf-alldep.jar -configtool 9080 0.0.0.0 /workdir > gatf.log 2>&1