//https://tomassetti.me/ebnf/

program
   : statement+
   ;

statement
   : 'open' browser
   | 'close'
   | 'sleep' integer
   | 'exec' code
   | 'if' paren_expr statement
   | 'if' paren_expr statement 'else' statement
   | 'while' paren_expr statement
   | 'do' statement 'while' paren_expr ';'
   | '{' statement* '}'
   | expr ';'
   | ';'
   ;

browser
	: 'chrome'
	| 'firefox'
	| 'edge'
	| 'safari'
	;

paren_expr
   : '(' expr ')'
   ;

expr
   : test
   | id '=' expr
   ;

test
   : sum
   | sum '<' sum
   ;

sum
   : term
   | sum '+' term
   | sum '-' term
   ;

term
   : id
   | integer
   | paren_expr
   ;

id
   : STRING
   ;

integer
   : INT
   ;


code
   : .+
   ;

STRING
   : [a-z]+
   ;


INT
   : [0-9]+
   ;

white space = ? white space characters ? ;

WS
   : [ rnt] -> skip
   ;