name: Build gatf

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    #if: contains(github.event.head_commit.message, '[docker_push]') && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Build gatf jar
      run: |
        mvn --quiet install
        docker build . --file Dockerfile
